# Generated by Django 4.2.7 on 2024-01-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_alter_history_player_one_alter_history_player_two_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(default='temp', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
