# Generated by Django 4.2.7 on 2023-11-29 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='enemy_score',
            new_name='player_one_score',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='own_score',
            new_name='player_two_score',
        ),
    ]
