# Generated by Django 4.2.7 on 2024-02-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0009_appuser_last_online_alter_appuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
