# Generated by Django 4.2.7 on 2024-03-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0011_history_game_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='draws',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='games',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='losses',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='wins',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
