# Use an official Python runtime as a parent image
FROM python:3.10-alpine

# Set the working directory in the container to /code
COPY requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt


# Make port 8000 available to the world outside this container
EXPOSE 8000
WORKDIR /code
# Run manage.py when the container launches
 CMD ["./start.sh"]